# Generated by Django 4.0.3 on 2022-03-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecificationvalue',
            options={'verbose_name': 'Product Specification Value', 'verbose_name_plural': 'Product Specification Values'},
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='specification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='store.productspecification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='value',
            field=models.CharField(default=0, help_text='Product specification value (maximum of 255 words', max_length=255, verbose_name='value'),
            preserve_default=False,
        ),
    ]
