# Generated by Django 4.0.3 on 2022-03-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
